# Enhancing Accessibility and Uniqueness of Hashtags in Instagram Dataset

In [2]:
# Importing the libraries
import pandas as pd  # Import the pandas library, which is used for data manipulation and analysis

# Installing the csv file
file_path = 'D:\\file.csv'  # Specify the file path of the CSV file

df = pd.read_csv(file_path, encoding='latin1')  # Read the CSV file into a DataFrame using the specified encoding

## Adding Unique Identifiers to DataFrame Rows

In [3]:
# Inserting a new column to uniquely identify each row

df.insert(0, 'ID', range(1, 1 + len(df)))  # Insert a new column at the beginning of the DataFrame with unique IDs for each row

pd.set_option('display.max_columns', None)  # Set the option to display all columns when printing the DataFrame
pd.set_option('display.max_colwidth', None)  # Set the option to display the full content of each column without truncation

df.head()  # Display the first few rows of the DataFrame

,ID,Impressions,From Home,From Hashtags,From Explore,From Other,Saves,Comments,Shares,Likes,Profile Visits,Follows,Caption,Hashtags
0,1,3920,2586,1028,619,56,98,9,5,162,35,2,Here are some of the most important data visualizations that every Financial Data Analyst/Scientist should know.,#finance #money #business #investing #investment #trading #stockmarket #data #datascience #dataanalysis #dataanalytics #datascientist #machinelearning #python #pythonprogramming #pythonprojects #pythoncode #artificialintelligence #ai #dataanalyst #amankharwal #thecleverprogrammer
1,2,5394,2727,1838,1174,78,194,7,14,224,48,10,Here are some of the best data science project ideas on healthcare. If you want to become a data science professional in the healthcare domain then you must try to work on these projects.,#healthcare #health #covid #data #datascience #dataanalysis #dataanalytics #datascientist #machinelearning #python #pythonprogramming #pythonprojects #pythoncode #artificialintelligence #ai #dataanalyst #amankharwal #thecleverprogrammer
2,3,4021,2085,1188,0,533,41,11,1,131,62,12,Learn how to train a machine learning model and giving inputs to your trained model to make predictions using Python.,#data #datascience #dataanalysis #dataanalytics #datascientist #machinelearning #python #pythonprogramming #pythonprojects #pythoncode #artificialintelligence #ai #deeplearning #machinelearningprojects #datascienceprojects #amankharwal #thecleverprogrammer #machinelearningmodels
3,4,4528,2700,621,932,73,172,10,7,213,23,8,Heres how you can write a Python program to detect whether a sentence is a question or not. The idea here is to find the words that we see in the beginning of a question in the beginning of a sentence.,#python #pythonprogramming #pythonprojects #pythoncode #pythonlearning #pythondeveloper #pythoncoding #pythonprogrammer #amankharwal #thecleverprogrammer #pythonprojects
4,5,2518,1704,255,279,37,96,5,4,123,8,0,Plotting annotations while visualizing your data is considered good practice to make the graphs self-explanatory. Here is an example of how you can annotate a graph using Python.,#datavisualization #datascience #data #dataanalytics #machinelearning #dataanalysis #artificialintelligence #python #datascientist #bigdata #deeplearning #dataviz #ai #analytics #technology #dataanalyst #programming #pythonprogramming #statistics #coding #businessintelligence #datamining #tech #business #computerscience #tableau #database #thecleverprogrammer #amankharwal

## Splitting Hashtags and Creating a New DataFrame with Unique Identifiers

In [4]:
new_df = []  # Initialize an empty list to store the new DataFrame
new_data = []  # Initialize an empty list to store the processed data

# Process the 'Hashtags' column in each row
for index, row in df.iterrows():  # Iterate over each row in the original DataFrame
    hashtags = row['Hashtags']  # Get the value of the 'Hashtags' column for the current row
    if pd.notna(hashtags):  # Check if the value is not NaN (not empty)
        hashtag_list = hashtags.split()  # Split the hashtags string into a list of individual hashtags
        for hashtag in hashtag_list:  # Iterate over each hashtag in the list
            new_data.append({'Original_Row_ID': index + 1, 'Hashtag': hashtag})  # Append a dictionary with the original row ID and hashtag to new_data

# Create the new DataFrame from the processed data
new_df = pd.DataFrame(new_data)

# Add an 'ID' column to the new DataFrame
new_df.insert(0, 'ID', range(1, 1 + len(new_df)))  # Insert a new column at the beginning with unique IDs for each row

# Display the new DataFrame
new_df.head(50) # Print the first 50 rows of the new DataFrame to verify the results

    ID  Original_Row_ID                  Hashtag
0    1                1                 #finance
1    2                1                   #money
2    3                1                #business
3    4                1               #investing
4    5                1              #investment
5    6                1                 #trading
6    7                1             #stockmarket
7    8                1                    #data
8    9                1             #datascience
9   10                1            #dataanalysis
10  11                1           #dataanalytics
11  12                1           #datascientist
12  13                1         #machinelearning
13  14                1                  #python
14  15                1       #pythonprogramming
15  16                1          #pythonprojects
16  17                1              #pythoncode
17  18                1  #artificialintelligence
18  19                1                      #ai
19  20                1             #dataanalyst
20  21                1             #amankharwal
21  22                1     #thecleverprogrammer
22  23                2              #healthcare
23  24                2                  #health
24  25                2                   #covid
25  26                2                    #data
26  27                2             #datascience
27  28                2            #dataanalysis
28  29                2           #dataanalytics
29  30                2           #datascientist
30  31                2         #machinelearning
31  32                2                  #python
32  33                2       #pythonprogramming
33  34                2          #pythonprojects
34  35                2              #pythoncode
35  36                2  #artificialintelligence
36  37                2                      #ai
37  38                2             #dataanalyst
38  39                2             #amankharwal
39  40                2     #thecleverprogrammer
40  41                3                    #data
41  42                3             #datascience
42  43                3            #dataanalysis
43  44                3           #dataanalytics
44  45                3           #datascientist
45  46                3         #machinelearning
46  47                3                  #python
47  48                3       #pythonprogramming
48  49                3          #pythonprojects
49  50                3              #pythoncode

## Cleaning and Resetting DataFrame for Hashtags

In [5]:
new_df = new_df.drop(columns=['ID']).reset_index(drop=True)  # Remove the 'ID' column and reset the index of the DataFrame without adding a new index column

In [6]:
# Remove the '#' character from the 'Hashtag' column
new_df['Hashtag'] = new_df['Hashtag'].str.replace('#', '')

# Display the first 50 rows of the updated DataFrame
print(new_df.head(50))

    Original_Row_ID                 Hashtag
0                 1                 finance
1                 1                   money
2                 1                business
3                 1               investing
4                 1              investment
5                 1                 trading
6                 1             stockmarket
7                 1                    data
8                 1             datascience
9                 1            dataanalysis
10                1           dataanalytics
11                1           datascientist
12                1         machinelearning
13                1                  python
14                1       pythonprogramming
15                1          pythonprojects
16                1              pythoncode
17                1  artificialintelligence
18                1                      ai
19                1             dataanalyst
20                1             amankharwal
21                1     thecleverprogrammer
22                2              healthcare
23                2                  health
24                2                   covid
25                2                    data
26                2             datascience
27                2            dataanalysis
28                2           dataanalytics
29                2           datascientist
30                2         machinelearning
31                2                  python
32                2       pythonprogramming
33                2          pythonprojects
34                2              pythoncode
35                2  artificialintelligence
36                2                      ai
37                2             dataanalyst
38                2             amankharwal
39                2     thecleverprogrammer
40                3                    data
41                3             datascience
42                3            dataanalysis
43                3           dataanalytics
44                3           datascientist
45                3         machinelearning
46                3                  python
47                3       pythonprogramming
48                3          pythonprojects
49                3              pythoncode

## Assigning Unique IDs to Hashtags

In [7]:
# Determine unique hashtags
unique_hashtags = new_df['Hashtag'].unique()  # Get an array of unique hashtags from the 'Hashtag' column

# Assign a 3-digit ID to each unique hashtag
hashtag_to_id = {hashtag: f"{i:03}" for i, hashtag in enumerate(unique_hashtags, 1)}  # Create a dictionary mapping each unique hashtag to a 3-digit ID

# Add a new column to the original DataFrame containing these IDs
new_df['Hashtag_ID'] = new_df['Hashtag'].map(hashtag_to_id)  # Map each hashtag in the 'Hashtag' column to its corresponding ID and add it to a new column

# Display the first 50 rows of the updated DataFrame
new_df.head(50)

    Original_Row_ID                 Hashtag Hashtag_ID
0                 1                 finance        001
1                 1                   money        002
2                 1                business        003
3                 1               investing        004
4                 1              investment        005
5                 1                 trading        006
6                 1             stockmarket        007
7                 1                    data        008
8                 1             datascience        009
9                 1            dataanalysis        010
10                1           dataanalytics        011
11                1           datascientist        012
12                1         machinelearning        013
13                1                  python        014
14                1       pythonprogramming        015
15                1          pythonprojects        016
16                1              pythoncode        017
17                1  artificialintelligence        018
18                1                      ai        019
19                1             dataanalyst        020
20                1             amankharwal        021
21                1     thecleverprogrammer        022
22                2              healthcare        023
23                2                  health        024
24                2                   covid        025
25                2                    data        008
26                2             datascience        009
27                2            dataanalysis        010
28                2           dataanalytics        011
29                2           datascientist        012
30                2         machinelearning        013
31                2                  python        014
32                2       pythonprogramming        015
33                2          pythonprojects        016
34                2              pythoncode        017
35                2  artificialintelligence        018
36                2                      ai        019
37                2             dataanalyst        020
38                2             amankharwal        021
39                2     thecleverprogrammer        022
40                3                    data        008
41                3             datascience        009
42                3            dataanalysis        010
43                3           dataanalytics        011
44                3           datascientist        012
45                3         machinelearning        013
46                3                  python        014
47                3       pythonprogramming        015
48                3          pythonprojects        016
49                3              pythoncode        017

In [8]:
# Save the changes to a new file (optional)
new_df.to_csv('D:\\Projects', index=False)